#!/bin/bash

# credits to https://www.youtube.com/@bwestbro
# I copied the script from https://www.youtube.com/watch?v=0e2I3G3PBuM and modiefied it to my likings

day=$(date +%-d)
utils=~/repos/AdventOfCode22/utils/
dir=~/repos/AdventOfCode22/day"$day"

mkdir -p "$dir"
cd "$dir" || exit
curl -b "$(cat "$utils/cookie")" "https://adventofcode.com/2022/day/$day/input" >"$dir/input.txt"
go mod init day"$day"
checkrunning # one of my scripts, checks if neovide is open and opens it if it's not
touch "$dir/sample.txt"
cp "$utils/template.go" "$dir/main.go"
/home/rik034/anaconda3/bin/nvr -l "$dir/main.go" # sends the file to nvim/neovide
/home/rik034/anaconda3/bin/nvr -l "$dir/sample.txt" # same thing
brave "https://adventofcode.com/2022/day/$day"
